import { Event, Testimonial, GalleryItem, SiteSettings, Artist } from './types';

export const siteSettings: SiteSettings = {
  socialUrls: {
    whatsapp: 'https://wa.me/94770000000',
    instagram: 'https://instagram.com/lfgentertainment',
    facebook: 'https://facebook.com/lfgentertainment',
    tiktok: 'https://tiktok.com/@lfgentertainment',
    youtube: 'https://youtube.com/c/lfgentertainment',
    email: 'mailto:hello@lfgentertainment.com',
  },
  offices: [
    {
      country: 'Malaysia',
      name: 'Malaysia Office',
      address: '20, Pusat Perniagaan Bestari, Jalan Permata 1A/KS09, Taman Perindustrian Air Hitam, 42000 Klang, Selangor',
    },
    {
      country: 'India',
      name: 'India Office',
      address: '669, 1st floor El Shaddai, 5th main road OMBR Layout, Banaswadi, Bangalore 560043',
    },
  ],
};

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    quote: "I've been to festivals in three countries. Nothing hits like an LFG night.",
    author: 'Shenali P.',
    event: 'Summer Bash 2025',
  },
  {
    id: 't2',
    quote: "The production was insane. Felt like Tomorrowland landed in Colombo.",
    author: 'Ravindu F.',
    event: 'Glow Festival',
  },
  {
    id: 't3',
    quote: "Went alone, left with twenty new friends and zero voice.",
    author: 'Amaya W.',
    event: 'Neon Night',
  },
  {
    id: 't4',
    quote: "VIP was worth every rupee. Separate bar, perfect view, zero queues.",
    author: 'Dinuk J.',
    event: 'Summer Bash 2025',
  },
];

// Reusable mock lineup generator to keep structure exact
const createLineup = (headlinerName: string): Artist[] => [
  {
    id: 'art-hl',
    name: headlinerName,
    photoUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=600&auto=format&fit=crop',
    role: 'Headliner',
  },
  {
    id: 'art-sup1',
    name: 'Diligent Noise',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup2',
    name: 'Kithula Live',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup3',
    name: 'DJ Shiyam',
    photoUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup4',
    name: 'Yohani (Special Set)',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup5',
    name: 'Ranidu',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup6',
    name: 'Iraj',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup7',
    name: 'Ashanthi',
    photoUrl: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup8',
    name: 'DJ Amber',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-sup9',
    name: 'Bathiya & Santhush',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    role: 'Support',
  },
  {
    id: 'art-op',
    name: 'The Opening Act',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
    role: 'Opener',
  },
];

export const mockEvents: Event[] = [
  {
    slug: 'senter-music-festival-2026',
    title: 'Senter Music Festival',
    startDate: '2026-10-30',
    endDate: '2026-10-31',
    doorsOpen: '6:00 PM',
    venue: {
      name: 'Port City Colombo',
      address: 'Port City waterfront, Colombo, Sri Lanka',
    },
    posterImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop',
    heroBanner: '/images/senter-music-festival-hero.jpg',
    shortDescription: "Sri Lanka's premier music festival — international headliners, homegrown talent, and a Halloween-weekend production unlike anything the island has seen.",
    fullDescription: "Senter Music Festival is Sri Lanka's premier music and entertainment experience, bringing together world-class performances, local talent, and unforgettable festival moments. Created by Senter Records, the festival celebrates music, culture, and creativity — a platform for Sri Lankan artists backed by international-standard production, immersive visuals, and full-scale EDM experiences. Top artists. Themed worlds. Premium hospitality. Senter Music Festival is the next generation of Sri Lankan entertainment — music lovers, creators, and communities on one iconic stage.",
    atmosphere: 'Two nights on the Port City waterfront. Halloween energy, festival scale. Pyro against the skyline, bass across the water, and a crowd that came to lose its voice.',
    quickFacts: [
      'International headline performances',
      'EDM & live music showcases',
      'Large-scale stage production',
      'Pyrotechnics & immersive visuals',
      'Halloween-themed experiences',
      'Food & beverage activations',
      'Premium hospitality areas',
      'Interactive audience experiences',
    ],
    lineup: createLineup('DJ Snake'),
    schedule: [
      { time: '6:00 PM', act: 'Gates Open' },
      { time: '7:00 PM', act: 'The Opening Act', stage: 'Main Stage' },
      { time: '9:00 PM', act: 'Local Artists Showcase', stage: 'Main Stage' },
      { time: '11:00 PM', act: 'DJ Snake', stage: 'Main Stage' },
      { time: '2:00 AM', act: 'Close' },
    ],
    ticketTiers: [
      {
        id: 'senter-ga',
        name: 'GA Pass',
        description: '2-day festival entry · Main arena access · F&B village',
        price: 15000,
        currency: 'LKR',
        perks: ['2-day festival entry', 'Main arena access', 'F&B village entry'],
        quantityTotal: 5000,
        quantitySold: 4200,
        isMain: false,
        sortOrder: 1,
      },
      {
        id: 'senter-viip',
        name: 'VIIP Pass',
        description: 'Everything in VIP · Stage-side platform · Private bar & lounge · Artist meet & greet · Concierge host · Exclusive merch pack',
        price: 55000,
        currency: 'LKR',
        perks: [
          'Everything in VIP',
          'Stage-side viewing platform',
          'Private bar & dedicated lounge access',
          'Exclusive artist meet & greet session',
          'Personal concierge host services',
          'Limited edition merch pack',
        ],
        quantityTotal: 100,
        quantitySold: 92,
        isMain: true,
        sortOrder: 2,
      },
      {
        id: 'senter-vip',
        name: 'VIP Pass',
        description: 'GA perks · Fast-track entry · Elevated viewing deck · Premium bars · VIP restrooms',
        price: 35000,
        currency: 'LKR',
        perks: [
          'All GA tier perks included',
          'Fast-track express entry lanes',
          'Elevated VIP-only viewing deck',
          'Dedicated premium beverage bars',
          'Air-conditioned VIP restrooms',
        ],
        quantityTotal: 1000,
        quantitySold: 1000, // Demo SOLD OUT state
        isMain: false,
        sortOrder: 3,
      },
    ],
    faqs: [
      { question: 'What time do gates open?', answer: '6 PM both nights. Come early — opening sets deserve a crowd too.' },
      { question: 'Is there an age limit?', answer: 'All ages welcome. Under-16s must be with an adult. Bars are 21+ with ID.' },
      { question: 'What can\'t I bring?', answer: 'Outside food/drinks, professional cameras, drones, and anything sharp. Small bags get searched.' },
      { question: 'Is re-entry allowed?', answer: 'No re-entry once scanned in. Plan your night.' },
      { question: 'What if it rains?', answer: 'The show goes on. Severe weather updates go out via email and socials.' },
      { question: 'Are tickets refundable?', answer: 'Tickets are non-refundable but transferable up to 48 hours before gates. See Terms.' },
    ],
  },
  {
    slug: 'neon-mirage-festival-2026',
    title: 'Neon Mirage Festival',
    startDate: '2026-12-05',
    endDate: '2026-12-06',
    doorsOpen: '5:00 PM',
    venue: {
      name: 'Sunway Lagoon',
      address: 'Kuala Lumpur, Malaysia',
    },
    posterImage: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=600&auto=format&fit=crop',
    heroBanner: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=1200&auto=format&fit=crop',
    shortDescription: 'A mirage of light, bass, and 20,000 believers. Join us in KL for our largest Southeast Asian gathering.',
    fullDescription: 'Neon Mirage returns to KL with an elevated production. Transforming Sunway Lagoon into a cyberpunk paradise of massive light fields, custom staging, and heavy bass lines. Featuring a handpicked lineup of international electronic acts and regional icons, Neon Mirage represents the pinnacle of modern nightlife experiences.',
    atmosphere: 'Neon pools, laser tunnels, and high-tempo electronica surrounding the surf beach. A playground of light and sound under the stars.',
    quickFacts: ['Massive laser displays', 'Water stage production', 'Cyberpunk environments', 'Interactive projection art'],
    lineup: createLineup('Amelie Lens'),
    schedule: [
      { time: '5:00 PM', act: 'Gates Open' },
      { time: '6:30 PM', act: 'Local DJs', stage: 'Mirage Stage' },
      { time: '9:00 PM', act: 'Support Acts', stage: 'Mirage Stage' },
      { time: '11:30 PM', act: 'Amelie Lens', stage: 'Mirage Stage' },
      { time: '2:00 AM', act: 'Close' },
    ],
    ticketTiers: [
      {
        id: 'neon-ga',
        name: 'General Admission',
        description: 'Single-day access to all main stages and festival grounds.',
        price: 25000,
        currency: 'LKR',
        perks: ['Single day entry', 'Access to Mirage Stage', 'F&B stalls access'],
        quantityTotal: 10000,
        quantitySold: 9800, // Almost gone
        isMain: true,
        sortOrder: 1,
      },
      {
        id: 'neon-vip',
        name: 'VIP Experience',
        description: 'Express entry, access to elevated VIP decks, private restrooms, and express bars.',
        price: 48000,
        currency: 'LKR',
        perks: ['Express entry lanes', 'Access to elevated viewing decks', 'Private air-conditioned toilets', 'VIP express bar'],
        quantityTotal: 1500,
        quantitySold: 1495, // Low stock demo (<10% remaining: only 5 left)
        isMain: false,
        sortOrder: 2,
      },
    ],
    faqs: [
      { question: 'Is the water park active?', answer: 'Selected areas of Sunway Lagoon will be open for themed visual experiences. Swimming is restricted.' },
    ],
  },
  {
    slug: 'underground-sessions-2027',
    title: 'Underground Sessions',
    startDate: '2027-01-23',
    endDate: '2027-01-23',
    doorsOpen: '10:00 PM',
    venue: {
      name: 'Secret Location',
      address: 'Singapore, SG',
    },
    posterImage: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=600&auto=format&fit=crop',
    heroBanner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop',
    shortDescription: 'No posters. No lineup reveal. Just trust us. A raw, industrial space for 800 people who live for the music.',
    fullDescription: 'Underground Sessions is our pure warehouse series. The location is sent to ticket holders 2 hours before the gates open. Stripped back production: just a dark warehouse, a heavy sound system, and visual projection maps on raw concrete.',
    atmosphere: 'Intimate, smoke-filled, red-lit industrial room. Focus is entirely on the sound. Strict no-camera policy.',
    quickFacts: ['Unannounced surprise lineup', 'Warehouse industrial environment', 'Custom heavy sound rig', 'Secret location drop'],
    lineup: createLineup('Surprise Headliner'),
    schedule: [
      { time: '10:00 PM', act: 'Opening DJ' },
      { time: '12:00 AM', act: 'Surprise Guest 1' },
      { time: '2:00 AM', act: 'Surprise Headliner' },
      { time: '5:00 AM', act: 'Close' },
    ],
    ticketTiers: [
      {
        id: 'ug-pass',
        name: 'All Access Session Pass',
        description: 'Entry to secret warehouse session and location coordinate dispatch.',
        price: 18000,
        currency: 'LKR',
        perks: ['Warehouse entry', 'Secret location coordinates dispatch via SMS', 'Complimentary first drink'],
        quantityTotal: 800,
        quantitySold: 795, // Low stock demo (only 5 left)
        isMain: true,
        sortOrder: 1,
      },
    ],
    faqs: [
      { question: 'When is location revealed?', answer: 'Coordinates are dispatched via SMS and Email at exactly 8:00 PM on Jan 23.' },
    ],
  },
];

export const mockPastEvents = [
  {
    slug: 'neon-night-bangkok',
    title: 'Neon Night',
    date: 'March 2025',
    location: 'Bangkok, Thailand 🇹🇭',
    oneLiner: 'The warehouse rave that started it all.',
    coverImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=600&auto=format&fit=crop',
  },
  {
    slug: 'summer-bash-2025-gold-coast',
    title: 'Summer Bash 2025',
    date: 'June 2025',
    location: 'Gold Coast, Australia 🇦🇺',
    oneLiner: 'Sunset to sunrise on the sand.',
    coverImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=600&auto=format&fit=crop',
  },
  {
    slug: 'glow-festival-jakarta',
    title: 'Glow Festival',
    date: 'December 2025',
    location: 'Jakarta, Indonesia 🇮🇩',
    oneLiner: '10,000 lights. One unforgettable night.',
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop',
  },
];

export const mockGalleries: GalleryItem[] = [
  {
    eventSlug: 'neon-night-bangkok',
    eventName: 'Neon Night',
    year: 2025,
    date: '15 March 2025',
    venueName: 'The Warehouse District, Bangkok',
    oneLiner: 'The warehouse rave that started it all.',
    tags: ['rave', 'warehouse', 'neon'],
    coverImage: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=1200&auto=format&fit=crop',
    media: [
      {
        id: 'nn1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'landscape',
        caption: 'The main stage drops deep house sets.',
      },
      {
        id: 'nn2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'portrait',
        caption: 'Laser arrays scanning the crowds.',
      },
      {
        id: 'nn3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'square',
        caption: 'Strict warehouse layouts, raw vibes.',
      },
      {
        id: 'nn4',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'landscape',
        caption: 'Intense energy from dawn to dusk.',
      },
    ],
  },
  {
    eventSlug: 'summer-bash-2025-gold-coast',
    eventName: 'Summer Bash 2025',
    year: 2025,
    date: '22 June 2025',
    venueName: 'Surfers Paradise, Gold Coast',
    oneLiner: 'Sunset to sunrise on the sand.',
    tags: ['beach party', 'sunset', 'edm'],
    coverImage: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=1200&auto=format&fit=crop',
    media: [
      {
        id: 'sb1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'landscape',
        caption: 'Stages set right on the beach sands.',
      },
      {
        id: 'sb2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'portrait',
        caption: 'Fire dancers setting the sunset ambiance.',
      },
      {
        id: 'sb3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'square',
        caption: 'Festival lights reflecting off the waves.',
      },
    ],
  },
  {
    eventSlug: 'glow-festival-jakarta',
    eventName: 'Glow Festival',
    year: 2025,
    date: '12 December 2025',
    venueName: 'Eco Park, Jakarta',
    oneLiner: '10,000 lights. One unforgettable night.',
    tags: ['glow', 'lights', 'strobe'],
    coverImage: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200&auto=format&fit=crop',
    media: [
      {
        id: 'gf1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'landscape',
        caption: '10,000 glow sticks flashing in unity.',
      },
      {
        id: 'gf2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'portrait',
        caption: 'Illuminated structures dotted across Eco Park.',
      },
      {
        id: 'gf3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop',
        aspectRatio: 'square',
        caption: 'The main pavilion at its peak glow state.',
      },
    ],
  },
];
